# Generated by Django 6.0.3 on 2026-03-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_posted_date_job_created_at_remove_job_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
